controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    robotnik_base_control:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

robotnik_base_control:
  ros__parameters:
    publish_rate: 50.0

    base_frame_id: summit_xl_base_footprint

    left_wheel_names:
      ["summit_xl_front_left_wheel_joint", "summit_xl_back_left_wheel_joint"]
    right_wheel_names:
      ["summit_xl_front_right_wheel_joint", "summit_xl_back_right_wheel_joint"]
    wheel_separation: 0.470
    wheel_radius: 0.11

    use_stamped_vel: false
