controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    robotnik_base_control:
      type: mecanum_drive_controller/MecanumDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

robotnik_base_control:
  ros__parameters:
    # Correct parameter names for mecanum controller
    front_left_wheel_command_joint_name: "summit_xl_front_left_wheel_joint"
    front_right_wheel_command_joint_name: "summit_xl_front_right_wheel_joint"
    rear_left_wheel_command_joint_name: "summit_xl_back_left_wheel_joint"
    rear_right_wheel_command_joint_name: "summit_xl_back_right_wheel_joint"

    # State interface names (usually same as command)
    front_left_wheel_state_joint_name: "summit_xl_front_left_wheel_joint"
    front_right_wheel_state_joint_name: "summit_xl_front_right_wheel_joint"
    rear_left_wheel_state_joint_name: "summit_xl_back_left_wheel_joint"
    rear_right_wheel_state_joint_name: "summit_xl_back_right_wheel_joint"

    kinematics.wheel_separation_x: 0.470 # Distance between front and rear axles
    kinematics.wheel_separation_y: 0.470 # Distance between left and right wheels
    kinematics.wheels_radius: 0.11

    base_frame_id: "summit_xl_base_footprint"
    odom_frame_id: "odom"
    enable_odom_tf: true
    publish_rate: 50.0

    use_stamped_vel: false
